export const AI_MODELS = [
  "Gemini 3.1 Flash Lite",
  "Gemini 2.5 Flash Lite",
  "Gemini 3.1 Pro Preview",
  "OpenAI 5.4 Mini",
  "OpenAI 5.4",
  "OpenAI 5.5",
  "OpenAI 5.3 Codex",
  "Open AI OSS 120B",
  "Claude Haiku 4.5",
  "DeepSeek V4 Flash",
  "DeepSeek V4 Pro",
  "Qwen3.6 Max",
  "Qwen3 235B A22B",
  "Qwen3 30B A3B Thinking 2507",
  "Claude Sonnet 4.6",
  "OpenAI 5.4 Nano",
  "Grok 4.20 Multi-Agent",
  "Grok 4.20",
  "Grok 4.3",
  "Kimi K2.6",
  "Gemini Nano Banana 2",
  "OpenAI GPT-5 Image Mini",
  "OpenAI GPT-5.4 Image 2",
] as const;

export type AIModel = (typeof AI_MODELS)[number];

export type ModelConfig = {
  modelId: string;
  provider: "openrouter";
  displayName: string;
  iconType:
  | "google"
  | "openai"
  | "anthropic"
  | "deepseek"
  | "huggingface"
  | "qwen"
  | "meta"
  | "x-ai"
  | "kimi";
  company: string;
  isPremium: boolean;
  isSuperPremium: boolean;
  hasReasoning: boolean;
  isFileSupported: boolean;
  isFast: boolean;
  isImageGeneration?: boolean;
  image2imageGen?: boolean;
  imageGenCreditCost?: number;
  description: string;
};

export const MODEL_CONFIGS = {
  "Gemini 3.1 Flash Lite": {
    modelId: "google/gemini-3.1-flash-lite",
    provider: "openrouter",
    displayName: "Gemini 3.1 Flash Lite",
    iconType: "google",
    company: "Google",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description: "Latest fast and efficient Gemini 3.1 Flash Lite model",
  },
  "Gemini 2.5 Flash Lite": {
    modelId: "google/gemini-2.5-flash-lite",
    provider: "openrouter",
    displayName: "Gemini 2.5 Flash Lite",
    iconType: "google",
    company: "Google",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: true,
    isFast: true,
    description: "Fast and efficient model from Google",
  },
  "Gemini 3.1 Pro Preview": {
    modelId: "google/gemini-3.1-pro-preview",
    provider: "openrouter",
    displayName: "Gemini 3.1 Pro Preview",
    iconType: "google",
    company: "Google",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: "Latest Google flagship model with 1M context",
  },
  "OpenAI 5.3 Codex": {
    modelId: "openai/gpt-5.3-codex",
    provider: "openrouter",
    displayName: "OpenAI 5.3 Codex",
    iconType: "openai",
    company: "OpenAI",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: "Latest OpenAI GPT-5.3 Codex flagship coding model with 400K context",
  },
  "OpenAI 5.4": {
    modelId: "openai/gpt-5.4",
    provider: "openrouter",
    displayName: "OpenAI 5.4",
    iconType: "openai",
    company: "OpenAI",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: "Latest OpenAI flagship model with 1M+ context",
  },
  "OpenAI 5.5": {
    modelId: "openai/gpt-5.5",
    provider: "openrouter",
    displayName: "OpenAI 5.5",
    iconType: "openai",
    company: "OpenAI",
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: "OpenAI GPT-5.5 next-gen flagship with 1M+ context and advanced reasoning",
  },
  "OpenAI 5.4 Mini": {
    modelId: "openai/gpt-5.4-mini",
    provider: "openrouter",
    displayName: "OpenAI 5.4 Mini",
    iconType: "openai",
    company: "OpenAI",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description: "Efficient mini version of OpenAI 5.4 with reasoning",
  },
  "Claude Haiku 4.5": {
    modelId: "anthropic/claude-haiku-4.5",
    provider: "openrouter",
    displayName: "Claude Haiku 4.5",
    iconType: "anthropic",
    company: "Anthropic",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description:
      "Anthropic's fastest and most efficient model with frontier-level intelligence, extended thinking, and exceptional coding capabilities (200K context)",
  },
  "Open AI OSS 120B": {
    modelId: "openai/gpt-oss-120b",
    provider: "openrouter",
    displayName: "Open AI OSS 120B",
    iconType: "openai",
    company: "OpenAI",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: true,
    description: "Fastest OSS Model by OpenAI",
  },
  "DeepSeek V4 Flash": {
    modelId: "deepseek/deepseek-v4-flash:free",
    provider: "openrouter",
    displayName: "DeepSeek V4 Flash",
    iconType: "deepseek",
    company: "DeepSeek",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: true,
    description: "Free DeepSeek V4 Flash with 1M context and reasoning",
  },
  "DeepSeek V4 Pro": {
    modelId: "deepseek/deepseek-v4-pro",
    provider: "openrouter",
    displayName: "DeepSeek V4 Pro",
    iconType: "deepseek",
    company: "DeepSeek",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: false,
    description: "DeepSeek V4 Pro flagship model with advanced reasoning",
  },
  "Qwen3.6 Max": {
    modelId: "qwen/qwen3.6-max-preview",
    provider: "openrouter",
    displayName: "Qwen3.6 Max",
    iconType: "qwen",
    company: "Alibaba",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: false,
    description:
      "Qwen3.6 Max is Alibaba's latest flagship with advanced reasoning and coding capabilities.",
  },
  "Qwen3 235B A22B": {
    modelId: "qwen/qwen3-235b-a22b",
    provider: "openrouter",
    displayName: "Qwen3 235B A22B",
    iconType: "qwen",
    company: "Alibaba",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: true,
    description:
      "Qwen3 235B A22B is a powerful model with advanced reasoning capabilities",
  },
  "Qwen3 30B A3B Thinking 2507": {
    modelId: "qwen/qwen3-30b-a3b-thinking-2507",
    provider: "openrouter",
    displayName: "Qwen3 30B A3B Thinking 2507",
    iconType: "qwen",
    company: "Alibaba",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: true,
    description:
      "Qwen3 30B A3B Thinking 2507 is a powerful model with advanced reasoning capabilities",
  },
  "Claude Sonnet 4.6": {
    modelId: "anthropic/claude-sonnet-4.6",
    provider: "openrouter",
    displayName: "Claude Sonnet 4.6",
    iconType: "anthropic",
    company: "Anthropic",
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: "Latest Anthropic flagship Sonnet model with 1M context and reasoning",
  },

  "OpenAI 5.4 Nano": {
    modelId: "openai/gpt-5.4-nano",
    provider: "openrouter",
    displayName: "OpenAI 5.4 Nano",
    iconType: "openai",
    company: "OpenAI",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description: "Fastest GPT-5.4 nano model with 400k context and reasoning.",
  },
  "Grok 4.20 Multi-Agent": {
    modelId: "x-ai/grok-4.20-multi-agent",
    provider: "openrouter",
    displayName: "Grok 4.20 Multi-Agent",
    iconType: "x-ai",
    company: "XAI",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: "Grok 4.20 multi-agent variant with 2M context.",
  },
  "Grok 4.20": {
    modelId: "x-ai/grok-4.20",
    provider: "openrouter",
    displayName: "Grok 4.20",
    iconType: "x-ai",
    company: "XAI",
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description:
      "Latest XAI flagship Grok 4.20 with 2M context, reasoning, and coding capabilities.",
  },
  "Grok 4.3": {
    modelId: "x-ai/grok-4.3",
    provider: "openrouter",
    displayName: "Grok 4.3",
    iconType: "x-ai",
    company: "XAI",
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description: "Faster Grok 4.3 variant with reasoning.",
  },
  "Kimi K2.6": {
    modelId: "moonshotai/kimi-k2.6",
    provider: "openrouter",
    displayName: "Kimi K2.6",
    iconType: "kimi",
    company: "Moonshot",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description: "Latest Moonshot Kimi K2.6 with reasoning and 262k context.",
  },
  "Gemini Nano Banana 2": {
    modelId: "google/gemini-3.1-flash-image-preview",
    provider: "openrouter",
    displayName: "Gemini Nano Banana 2",
    iconType: "google",
    company: "Google",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    isImageGeneration: true,
    image2imageGen: true,
    imageGenCreditCost: 10,
    description:
      "Latest Gemini 3.1 Flash Image (Nano Banana 2) for AI image generation via OpenRouter",
  },
  "OpenAI GPT-5 Image Mini": {
    modelId: "openai/gpt-5-image-mini",
    provider: "openrouter",
    displayName: "OpenAI GPT-5 Image Mini",
    iconType: "openai",
    company: "OpenAI",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: true,
    isFast: false,
    isImageGeneration: true,
    image2imageGen: true,
    imageGenCreditCost: 5,
    description:
      "Fast and efficient image generation from OpenAI via OpenRouter",
  },
  "OpenAI GPT-5.4 Image 2": {
    modelId: "openai/gpt-5.4-image-2",
    provider: "openrouter",
    displayName: "OpenAI GPT-5.4 Image 2",
    iconType: "openai",
    company: "OpenAI",
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    isImageGeneration: true,
    image2imageGen: true,
    imageGenCreditCost: 8,
    description:
      "Latest OpenAI GPT-5.4 Image 2 model for high-quality image generation via OpenRouter",
  },
} as const satisfies Record<AIModel, ModelConfig>;

export const getModelConfig = (modelName: AIModel): ModelConfig => {
  const config = MODEL_CONFIGS[modelName];
  if (!config) {
    console.error(
      `Model config not found for: ${modelName}. Available models:`,
      Object.keys(MODEL_CONFIGS),
    );
    // Return a fallback config for the first available model
    return MODEL_CONFIGS["Gemini 2.5 Flash Lite"];
  }
  return config;
};
