export const AI_MODELS = [
  'Gemini 2.5 Flash',
  'Gemini 2.5 Flash Lite',
  'OpenAI 5 Mini',
  "OpenAI 5",
  'OpenAI o4-mini',
  'Open AI OSS 120B',
  'Claude Haiku 3.5',
  'DeepSeek R1 Fast',
  'DeepSeek V3.1',
  'Qwen3 235B A22B',
  'Claude Sonnet 4',
  'Gemini 2.5 Pro',
  'OpenAI 5 Nano',
  'Grok 3 Mini',
  'FLUX.1 [schnell]',
  'FLUX.1 Dev',
  'FLUX.1 Kontext [dev]',
  'Stable Defusion 3',
  'Juggernaut Pro',
] as const;

export type AIModel = (typeof AI_MODELS)[number];

export type ModelConfig = {
  modelId: string;
  provider: 'openrouter' | 'runware';
  displayName: string;
  iconType: 'google' | 'openai' | 'anthropic' | 'deepseek' | 'huggingface' | 'qwen' | 'meta' | 'x-ai' | 'runware';
  company: string;
  isPremium: boolean;
  isSuperPremium: boolean;
  hasReasoning: boolean;
  isFileSupported: boolean;
  isFast: boolean;
  isImageGeneration?: boolean;
  image2imageGen?: boolean;
  description: string;
};

export const MODEL_CONFIGS = {
  'Gemini 2.5 Flash': {
    modelId: 'google/gemini-2.5-flash',
    provider: 'openrouter',
    displayName: 'Gemini 2.5 Flash',
    iconType: 'google',
    company: 'Google',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: true,
    isFast: true,
    description: 'Fast and efficient model from Google',
  },
  'Gemini 2.5 Flash Lite': {
    modelId: 'google/gemini-2.5-flash-lite',
    provider: 'openrouter',
    displayName: 'Gemini 2.5 Flash Lite',
    iconType: 'google',
    company: 'Google',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: true,
    isFast: true,
    description: 'Fast and efficient model from Google',
  },
  'OpenAI 5': {
    modelId: 'openai/gpt-5',
    provider: 'openrouter',
    displayName: 'OpenAI 5',
    iconType: 'openai',
    company: 'OpenAI',
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: 'Latest OpenAI flagship model',
  },
  'OpenAI 5 Mini': {
    modelId: 'openai/gpt-5-mini',
    provider: 'openrouter',
    displayName: 'OpenAI 5 Mini',
    iconType: 'openai',
    company: 'OpenAI',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: true,
    isFast: true,
    description: 'Efficient mini version of OpenAI 5',
  },

  'OpenAI o4-mini': {
    modelId: 'openai/o4-mini',
    provider: 'openrouter',
    displayName: 'OpenAI o4-mini',
    iconType: 'openai',
    company: 'OpenAI',
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description: 'OpenAI\'s latest mini model with advanced reasoning capabilities and coding capabilities',
  },
  'Claude Haiku 3.5': {
    modelId: 'anthropic/claude-3.5-haiku',
    provider: 'openrouter',
    displayName: 'Claude Haiku 3.5',
    iconType: 'anthropic',
    company: 'Anthropic',
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: true,
    isFast: true,
    description: 'Anthropic\'s model for fast responses',
  },
  'Open AI OSS 120B': {
    modelId: 'openai/gpt-oss-120b',
    provider: 'openrouter',
    displayName: 'Open AI OSS 120B',
    iconType: 'openai',
    company: 'OpenAI',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: true,
    description: 'Fastest OSS Model by OpenAI',
  },
  'DeepSeek R1 Fast': {
    modelId: 'deepseek/deepseek-r1-0528-qwen3-8b',
    provider: 'openrouter',
    displayName: 'DeepSeek R1 Fast',
    iconType: 'deepseek',
    company: 'DeepSeek',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: true,
    description: 'Deepseek Best in the class latest advanced reasoning model',
  },
  'DeepSeek V3.1': {
    modelId: 'deepseek/deepseek-chat-v3.1',
    provider: 'openrouter',
    displayName: 'DeepSeek V3.1',
    iconType: 'deepseek',
    company: 'DeepSeek',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: false,
    isFast: true,
    description: 'Deepseek Best Model For Coding',
  },
  'Qwen3 235B A22B': {
    modelId: 'qwen/qwen3-235b-a22b:free',
    provider: 'openrouter',
    displayName: 'Qwen3 235B A22B',
    iconType: 'qwen',
    company: 'Alibaba',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: false,
    isFast: true,
    description: 'Qwen3 235B A22B is a powerful model with advanced reasoning capabilities',
  },
  'Claude Sonnet 4': {
    modelId: 'anthropic/claude-sonnet-4',
    provider: 'openrouter',
    displayName: 'Claude Sonnet 4',
    iconType: 'anthropic',
    company: 'Anthropic',
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: false,
    isFileSupported: true,
    isFast: false,
    description: 'Best in the class OpenAI model with advanced reasoning',
  },
  'Gemini 2.5 Pro': {
    modelId: 'google/gemini-2.5-pro',
    provider: 'openrouter',
    displayName: 'Gemini 2.5 Pro',
    iconType: 'google',
    company: 'Google',
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: true,
    isFileSupported: true,
    isFast: false,
    description: 'Best in the class Google model with advanced reasoning and coding capabilities',
  },
  'OpenAI 5 Nano': {
    modelId: 'openai/gpt-5-nano',
    provider: 'openrouter',
    displayName: 'OpenAI 5 Nano',
    iconType: 'openai',
    company: 'OpenAI',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: true,
    isFast: true,
    description: 'Fastest model from OpenAI.',
  },
  'Grok 3 Mini': {
    modelId: 'x-ai/grok-3-mini-beta',
    provider: 'openrouter',
    displayName: 'Grok 3 Mini',
    iconType: 'x-ai',
    company: 'XAI',
    isPremium: false,
    isSuperPremium: false,
    hasReasoning: true,
    isFileSupported: true,
    isFast: true,
    description: 'Fastest model from XAI with advanced reasoning.',
  },
  'FLUX.1 [schnell]': {
    modelId: 'runware:100@1',
    provider: 'runware',
    displayName: 'Flux Model Classic',
    iconType: 'runware',
    company: 'Runware',
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: false,
    isFast: true,
    isImageGeneration: true,
    description: 'For Ultra-fast Image Generation. FHD',
  },
  'FLUX.1 Dev': {
    modelId: 'runware:101@1',
    provider: 'runware',
    displayName: 'Flux Dev',
    iconType: 'runware',
    company: 'Runware',
    isPremium: true,
    isSuperPremium: false,
    hasReasoning: false,
    isFileSupported: false,
    isFast: true,
    isImageGeneration: true,
    description: 'Image Generation for Developers. FHD',
  },
  'Stable Defusion 3': {
    modelId: 'runware:5@1',
    provider: 'runware',
    displayName: 'Stable Diffusion 3',
    iconType: 'runware',
    company: 'Runware',
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: false,
    isFileSupported: false,
    isFast: false,
    isImageGeneration: true,
    description: 'For Realistic Image Generation. FHD',
  },
  'Juggernaut Pro': {
    modelId: 'rundiffusion:130@100',
    provider: 'runware',
    displayName: 'Juggernaut Pro (FHD)',
    iconType: 'runware',
    company: 'Runware',
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: false,
    isFileSupported: false,
    isFast: false,
    isImageGeneration: true,
    description: 'For Ultra Realistic Image Generation. FHD',
  },
  'FLUX.1 Kontext [dev]': {
    modelId: 'runware:106@1',
    provider: 'runware',
    displayName: 'Flux Image to Image',
    iconType: 'runware',
    company: 'Runware',
    isPremium: false,
    isSuperPremium: true,
    hasReasoning: false,
    isFileSupported: true,
    isFast: false,
    isImageGeneration: true,
    image2imageGen: true,
    description: 'Image-to-Image generation with Context, FHD',
  },
} as const satisfies Record<AIModel, ModelConfig>;

export const getModelConfig = (modelName: AIModel): ModelConfig => {
  const config = MODEL_CONFIGS[modelName];
  if (!config) {
    console.error(`Model config not found for: ${modelName}. Available models:`, Object.keys(MODEL_CONFIGS));
    // Return a fallback config for the first available model
    return MODEL_CONFIGS['OpenAI 5 Mini'];
  }
  return config;
};
